<a href="https://colab.research.google.com/github/choseonggeon/python/blob/main/exam2_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 테스트

In [3]:
x = 3
y = 0.5
b = True
c = False
print(x+y+b+c)


4.5


In [ ]:
y = x * 10
y


30

In [4]:
x = [1,2,3,5,100]

In [8]:
x.append(200)
x

[1, 2, 3, 5, 100, 200]

In [9]:
x[1:4]

[2, 3, 5]

In [10]:
(a,b) = (8,9)

In [11]:
print(a)

8


In [12]:
dic={"a":5, "b":8}
print(dic["a"])
dic["c"]=1000
print(dic)

5
{'a': 5, 'b': 8, 'c': 1000}


SyntaxError: ignored

In [20]:
x = 13
if x > 10:
  print("more than 10")
else:
  print("less than 10")

more than 10


In [17]:
x=[1,2,5,10]
for i in x:
  print(i*10)

10
20
50
100


In [18]:
tag = 0
while tag < 5 :
  print ('OK')
  tag = tag +1

OK
OK
OK
OK
OK


In [21]:
x = [1,2,5,10]
print(x*3)

[1, 2, 5, 10, 1, 2, 5, 10, 1, 2, 5, 10]


In [22]:
type(x)

list

In [26]:
import numpy as np
y = np.array(x)
print(y*3)

[ 3  6 15 30]


In [24]:
type(y)

numpy.ndarray

In [27]:
z=list(y) ; z

[1, 2, 5, 10]

In [28]:
x=[[1,2,3,],[4,5,6]]

In [29]:
print(x)

[[1, 2, 3], [4, 5, 6]]


In [31]:
y=np.array(x) ; y*10

array([[10, 20, 30],
       [40, 50, 60]])

In [32]:
y+1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006]])

In [34]:
import pandas as pd
df = pd.DataFrame(x) ; df

0  1  2
0  1  2  3
1  4  5  6

In [35]:
df = pd.DataFrame(x, columns=["a","b","c"]) ; df

a  b  c
0  1  2  3
1  4  5  6

In [36]:
df = pd.DataFrame(x, columns=["키","몸무게","나이"]) ; df

키  몸무게  나이
0  1    2   3
1  4    5   6

In [37]:
df.values

array([[1, 2, 3],
       [4, 5, 6]])